<a href="https://colab.research.google.com/github/panda6999/panda6999-Home_task01_id_2215151046.ipynb/blob/main/Home_Task_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#with fixed seed
np.random.seed(10)
fixed_seed_matrix = np.random.randint(1, 51, (3, 3))
print("Matrx With fixed seed:")
print(fixed_seed_matrix)


# Without setting a seed
random_matrix = np.random.randint(1, 51, (3,3))
print("\nMatrix Without fixed seed:")
print(random_matrix)

Matrx With fixed seed:
[[10 37 16]
 [ 1 50 29]
 [26 30 49]]

Matrix Without fixed seed:
[[30 50  9]
 [10  1 43]
 [41 37 17]]
